'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { translations } from '@/lib/i18n';
import { useLanguage } from '@/components/LanguageProvider';

type FeedbackOption = 'love_it' | 'needs_improvement' | 'not_needed';

export default function AIFeaturesPage() {
  const { lang } = useLanguage();
  const { data: session } = useSession();
  const t = translations[lang];

  const [summaryRating, setSummaryRating] = useState<FeedbackOption | null>(null);
  const [voiceRating, setVoiceRating] = useState<FeedbackOption | null>(null);
  const [wantsPremium, setWantsPremium] = useState<boolean | null>(null);
  const [additionalFeedback, setAdditionalFeedback] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);

  const handleSubmit = async () => {
    if (!session) {
      alert('Please login to submit feedback');
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await fetch('/api/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'ai_features',
          summaryRating,
          voiceRating,
          wantsPremium,
          additionalFeedback
        })
      });

      if (response.ok) {
        setIsSubmitted(true);
      } else {
        alert('Failed to submit feedback. Please try again.');
      }
    } catch {
      alert('Failed to submit feedback. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-white dark:from-gray-900 dark:to-gray-800">
      {/* Header */}
      <header className="bg-gradient-to-r from-emerald-700 via-emerald-600 to-teal-600 text-white">
        <div className="h-1.5 bg-gradient-to-r from-yellow-400 via-red-500 to-yellow-400"></div>
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <span className="text-2xl">🦅</span>
              <span className="text-xl font-bold">Sarawak News</span>
            </Link>
            <Link href="/" className="text-emerald-100 hover:text-white text-sm">
              ← {t.backToNews || 'Back to News'}
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-12">
        {/* Title */}
        <div className="text-center mb-8">
          <div className="text-6xl mb-4">🤖</div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            AI Features - Beta
          </h1>
          <p className="text-gray-600 dark:text-gray-300">
            We're exploring AI-powered features to enhance your news experience
          </p>
        </div>

        {/* Experimental Notice */}
        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-2xl p-6 mb-8">
          <h2 className="font-semibold text-amber-800 dark:text-amber-300 mb-3 flex items-center gap-2">
            <span>⚠️</span>
            Experimental Features
          </h2>
          <p className="text-amber-700 dark:text-amber-400 text-sm mb-4">
            These AI features are still in early development. We're testing and improving them based on your feedback.
          </p>
          <ul className="space-y-2 text-amber-700 dark:text-amber-400 text-sm">
            <li className="flex items-start gap-2">
              <span className="mt-0.5">🔊</span>
              <div>
                <strong>Voice Quality:</strong> Currently using browser's built-in text-to-speech.
                Voice quality varies by device and may sound robotic on some browsers.
              </div>
            </li>
            <li className="flex items-start gap-2">
              <span className="mt-0.5">📝</span>
              <div>
                <strong>AI Summary:</strong> Summaries are generated by AI and may occasionally miss
                important details or contain inaccuracies. Always read the original article for full information.
              </div>
            </li>
          </ul>
        </div>

        {/* Current Features */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-6 mb-8">
          <h2 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <span>✨</span>
            Current AI Features (Free)
          </h2>
          <div className="space-y-4">
            <div className="flex items-start gap-3 p-3 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
              <span className="text-2xl">🤖</span>
              <div>
                <h3 className="font-medium text-purple-800 dark:text-purple-300">AI Summary</h3>
                <p className="text-sm text-purple-600 dark:text-purple-400">
                  Quick summaries of news articles powered by AI. Click the AI button on any news item.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-3 p-3 bg-emerald-50 dark:bg-emerald-900/20 rounded-lg">
              <span className="text-2xl">🔊</span>
              <div>
                <h3 className="font-medium text-emerald-800 dark:text-emerald-300">Listen to Summary</h3>
                <p className="text-sm text-emerald-600 dark:text-emerald-400">
                  Text-to-speech using your browser's voices. Works offline, no internet required.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Future Possibilities */}
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 rounded-2xl p-6 mb-8">
          <h2 className="font-semibold text-indigo-800 dark:text-indigo-300 mb-4 flex items-center gap-2">
            <span>🚀</span>
            Premium AI Options (Under Consideration)
          </h2>
          <p className="text-indigo-700 dark:text-indigo-400 text-sm mb-4">
            We're considering premium AI features with higher quality. Your feedback will help us decide:
          </p>
          <div className="space-y-3">
            <div className="flex items-start gap-3 p-3 bg-white/50 dark:bg-gray-800/50 rounded-lg">
              <span className="text-xl">🎙️</span>
              <div>
                <h3 className="font-medium text-indigo-800 dark:text-indigo-300">Natural Voice TTS</h3>
                <p className="text-sm text-indigo-600 dark:text-indigo-400">
                  Human-like voices using ElevenLabs or similar services.
                  More natural, expressive, and easier to listen to.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-3 p-3 bg-white/50 dark:bg-gray-800/50 rounded-lg">
              <span className="text-xl">🧠</span>
              <div>
                <h3 className="font-medium text-indigo-800 dark:text-indigo-300">Advanced Summaries</h3>
                <p className="text-sm text-indigo-600 dark:text-indigo-400">
                  More detailed and accurate summaries using premium AI models
                  like GPT-4 or Claude.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Feedback Form */}
        {isSubmitted ? (
          <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-2xl p-8 text-center">
            <div className="text-5xl mb-4">🙏</div>
            <h2 className="text-xl font-bold text-emerald-800 dark:text-emerald-300 mb-2">
              Thank You for Your Feedback!
            </h2>
            <p className="text-emerald-600 dark:text-emerald-400">
              Your input helps us improve Sarawak News for everyone.
            </p>
            <Link
              href="/"
              className="inline-block mt-6 px-6 py-3 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-colors"
            >
              Back to News
            </Link>
          </div>
        ) : (
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-6">
            <h2 className="font-semibold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
              <span>📋</span>
              Share Your Feedback
            </h2>

            {/* AI Summary Rating */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                How do you find the AI Summary feature?
              </label>
              <div className="flex flex-wrap gap-2">
                {[
                  { value: 'love_it', label: '😍 Love it!', color: 'emerald' },
                  { value: 'needs_improvement', label: '🤔 Needs improvement', color: 'amber' },
                  { value: 'not_needed', label: '👎 Don\'t need it', color: 'red' }
                ].map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setSummaryRating(option.value as FeedbackOption)}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                      summaryRating === option.value
                        ? option.color === 'emerald' ? 'bg-emerald-500 text-white'
                        : option.color === 'amber' ? 'bg-amber-500 text-white'
                        : 'bg-red-500 text-white'
                        : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Voice Rating */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                How do you find the Text-to-Speech voice quality?
              </label>
              <div className="flex flex-wrap gap-2">
                {[
                  { value: 'love_it', label: '😍 Good enough!', color: 'emerald' },
                  { value: 'needs_improvement', label: '🤔 Could be better', color: 'amber' },
                  { value: 'not_needed', label: '👎 Too robotic', color: 'red' }
                ].map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setVoiceRating(option.value as FeedbackOption)}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                      voiceRating === option.value
                        ? option.color === 'emerald' ? 'bg-emerald-500 text-white'
                        : option.color === 'amber' ? 'bg-amber-500 text-white'
                        : 'bg-red-500 text-white'
                        : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Premium Interest */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                Would you pay for premium AI features (better voice, better summaries)?
              </label>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => setWantsPremium(true)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                    wantsPremium === true
                      ? 'bg-purple-500 text-white'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                  }`}
                >
                  💰 Yes, I'd consider it
                </button>
                <button
                  onClick={() => setWantsPremium(false)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                    wantsPremium === false
                      ? 'bg-gray-500 text-white'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                  }`}
                >
                  🆓 Free is enough for me
                </button>
              </div>
            </div>

            {/* Additional Comments */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                Any other thoughts or suggestions?
              </label>
              <textarea
                value={additionalFeedback}
                onChange={(e) => setAdditionalFeedback(e.target.value)}
                placeholder="Tell us what you think..."
                rows={4}
                className="w-full px-4 py-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* Submit Button */}
            <button
              onClick={handleSubmit}
              disabled={isSubmitting || !session}
              className="w-full py-3 px-6 bg-gradient-to-r from-emerald-500 to-teal-600 text-white font-semibold rounded-lg hover:from-emerald-600 hover:to-teal-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isSubmitting ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Submitting...
                </span>
              ) : !session ? (
                'Login to Submit Feedback'
              ) : (
                'Submit Feedback'
              )}
            </button>

            {!session && (
              <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-3">
                Please <Link href="/api/auth/signin" className="text-emerald-600 hover:underline">login</Link> to submit feedback.
              </p>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
